package com.xp.wx.spellbook.douyin.mirror;

import com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.live.Methods;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\u000e\n\u0000\n\u0002\u0010 \n\u0002\u0010\u0000\n\u0002\b\u0003\"\u0017\u0010\u0000\u001a\b\u0012\u0004\u0012\u00020\u00020\u0001¢\u0006\b\n\u0000\u001a\u0004\b\u0003\u0010\u0004¨\u0006\u0005"}, d2 = {"MirrorMethods", "", "", "getMirrorMethods", "()Ljava/util/List;", "app_release"}, k = 2, mv = {1, 1, 13})
/* compiled from: MirrorMethods.kt */
public final class MirrorMethodsKt {
    private static final List<Object> MirrorMethods = CollectionsKt.listOf(Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.live.base.c.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.live.f.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.live.network.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.chatroom.presenter.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.chatroom.ui.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.chatroom.viewmodule.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.chatroom.viewmodule.digg.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.gift.platform.core.api.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.gift.platform.core.manager.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.livecommerce.b.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.livecommerce.h.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.livecommerce.j.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdk.module.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.android.livesdkapi.depend.g.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.common.utility.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.ies.ugc.appcontext.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.im.core.c.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.bytedance.retrofit2.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.account.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.account.k.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.base.api.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.common.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.feed.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.following.repository.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.im.sdk.chat.model.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.im.sdk.utils.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.profile.presenter.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.update.Methods.INSTANCE, com.xp.wx.spellbook.douyin.mirror.com.ss.android.ugc.aweme.userservice.Methods.INSTANCE);

    public static final List<Object> getMirrorMethods() {
        return MirrorMethods;
    }
}
